/**
 *
 */
#include <stdbool.h>
#include "default_config.h"

#define DUAL_CHIP_ENABLE true
#define SECONDARY_CHIP_MODE true
#define OLD_SWARM_BOARD_MODE true
#define DEVELOPMENT_KIT_MODE true

#define STATUS_LED_PWM_TOP_VALUE STATUS_LED_PWM_TOP_VALUE_DEFAULT
#define STATUS_LED_PWM_CLOCK_SPEED STATUS_LED_PWM_CLOCK_SPEED_DEFAULT

#define BMX160_ENABLE true
#define LPS22HB_ENABLE truel

#define NRF_LOG_USED true

#define GPIO_PIN_NOT_USED 0xff

#define SPI_BUFFER_LENGTH_DEFAULT 10

#if DUAL_CHIP_ENABLE
#define SECONDARY_CHIP SECONDARY_CHIP_MODE
#else
#define SECONDARY_CHIP SECONDARY_CHIP_DEFAULT_CONFIG
#endif